"""
Django settings for demo_project project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-tadidada-tadadada-tadidadada-tatatata')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [os.environ.get('ALLOWED_HOST', '*')]


# Application definition

INSTALLED_APPS = [
    'library',
    'django_forest',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    # we don't need theses one for demo
    # 'django.contrib.admin',
    # 'django.contrib.sessions',
    # 'django.contrib.messages',
    # 'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'demo_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'demo_project.wsgi.application'

FOREST_IGNORE_DJANGO_MODELS = [
    'auth_group',
    'auth_user_groups',
    'auth_user',
    'auth_user_user_permissions',
    'auth_group_permissions',
    'auth_permission',
    'Permission',
    'django_content_type',
]
FOREST_IGNORE_RAILS_MODELS = [
    'failed_jobs',
    'migrations',
    'personal_access_tokens',
    'password_resets',
    # 'users',
]

FOREST = {
    'FOREST_URL': os.environ.get("FOREST_URL", "https://api.development.forestadmin.com"),
    'FOREST_ENV_SECRET': os.environ.get('FOREST_ENV_SECRET', '8e9ceb3e6476e84fd49a7ce46a26e519662417b2017a9b4f693e33ef0dac2950'),
    'FOREST_AUTH_SECRET': os.environ.get('FOREST_AUTH_SECRET', 'f3db1caad65fe3f09f66811cbebb310dd7054307a34c1774'),
    'EXCLUDED_MODELS': FOREST_IGNORE_DJANGO_MODELS + FOREST_IGNORE_RAILS_MODELS,
}
APPEND_SLASH=False


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.postgresql_psycopg2'),
        'NAME': os.environ.get('DB_NAME', 'django-demo'),
        'USER': os.environ.get('DB_USER', 'django-demo'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
    },
}

MANAGE_MODELS=os.environ.get('MANAGE_MODELS', 'False').lower() == 'true'


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
